name: Build-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

stages:
- stage: Build
  displayName: Build PSDesiredStateConfiguration module
  jobs:
  - job: BuildPkg
    displayName: Build Package
    pool:
      vmImage: windows-latest
    steps:
    - template: templates/ci-build.yml
    - pwsh: |
        Write-Verbose "BUILD_OUTPUT_PATH- $env:BUILD_OUTPUT_PATH" -Verbose
        Write-Verbose "SIGNED_OUTPUT_PATH- $env:SIGNED_OUTPUT_PATH" -Verbose
        Copy-Item $env:BUILD_OUTPUT_PATH $env:SIGNED_OUTPUT_PATH -Recurse -Force
      displayName: Build Signing Placeholder
    - pwsh: |
        $(Build.SourcesDirectory)/build.ps1 -Publish -Signed
      displayName: Publish
      timeoutInMinutes: 10