blank_issues_enabled: false
contact_links:
  - name: Documentation Issue
    url: https://github.com/MicrosoftDocs/PowerShell-Docs-DSC
    about: Please open issues on documentation for PSDesiredStateConfiguration here.
